version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:example@db:5432/bobr
volumes:
  db-data:
 